Add 2.6 kernel support to ofpath
* ybin/ofpath: Add support for 2.6.4+ kernels with sysfs mounted.
git-archimport-id: erbenson@alaska.net--public/yaboot--devel--1.3--patch-66

diff --git a/ybin/ofpath b/ybin/ofpath
--- a/ybin/ofpath
+++ b/ybin/ofpath
@@ -27,7 +27,7 @@
 
 PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"
 PRG="${0##*/}"
-VERSION=1.0.5
+VERSION=1.0.6-pre1
 DEBUG=0
 export LC_COLLATE=C
 
@@ -323,11 +323,32 @@ ide_ofpath()
 	echo 1>&2 "$PRG: BUG: IDEBUS == NULL"
 	return 1
     fi
-    local OF1275IDE="/proc/ide/$IDEBUS/devspec"
+
+    case "$(uname -r)" in
+	2.5.*|2.6.0*|2.6.1|2.6.1-*|2.6.2|2.6.2-*|2.6.3|2.6.3-*)
+	    echo "$PRG: Linux kernel `uname -r` is not supported"
+	    return 1
+	    ;;
+	2.6.*|2.7.*)
+	    if ! (grep -q ^sysfs /proc/mounts 2> /dev/null) ; then
+		echo 1>&2 "$PRG: sysfs must be mounted for ofpath to support this system"
+		return 1
+	    fi
+	    local SYS="$(m=`grep ^sysfs /proc/mounts | head -n 1` ; echo `d=${m#* };echo ${d%% *}`)"
+	    if [ -z "$SYS" -o ! -d "$SYS" ] ; then
+		echo 2>&1 "$PRG: Unable to determine sysfs mountpoint"
+		return 1
+	    fi
+	    local OF1275IDE="${SYS}/block/${DEVNODE}/device/../../devspec"
+	    ;;
+	*)
+	    local OF1275IDE="/proc/ide/$IDEBUS/devspec"
+	    ;;
+    esac
 
     if [ ! -f "$OF1275IDE" ] ; then
 	case "$(cat /proc/device-tree/model)" in
-	    "PowerMac3,6")
+	    PowerMac3*|PowerMac4*|PowerMac5*|PowerMac6*|PowerMac7*|X*)
 		local CDROM="$(grep "^drive name:" /proc/sys/dev/cdrom/info 2> /dev/null | grep $DEVNODE)"
 		if [ -z "$CDROM" ] ; then
 		    echo 1>&2 "$PRG: WARNING: Your kernel is too old for proper support, device may be innaccurate."
